[workspace]
members = [ 
    "bindings/tbdex_uniffi", "crates/pfi_exemplar_integration_test",
    "crates/tbdex",
]
default-members = [
    "crates/tbdex",
]
resolver = "2"

[workspace.package]
homepage = "https://github.com/TBD54566975/tbdex-rs"
repository = "https://github.com/TBD54566975/tbdex-rs.git"
license-file = "LICENSE"

[workspace.dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
web5 = { git = "https://github.com/TBD54566975/web5-rs", rev = "2eed09c9eb97c4a9cd046a57cec450c816dc38e2" }
